# Generated by Django 5.2.16 on 2026-08-21 11:15

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0303_alter_order_organizer_alter_orderposition_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', i18nfield.fields.I18nTextField()),
                ('help_text', i18nfield.fields.I18nTextField()),
                ('identifier', models.CharField(max_length=190)),
                ('type', models.CharField(max_length=1)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_questions', to='pretixbase.event')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'unique_together': {('event', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='OrderAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_question_answers', to='pretixbase.order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretix_order_questions.orderquestion')),
            ],
            options={
                'unique_together': {('order', 'question')},
            },
        ),
        migrations.CreateModel(
            name='OrderQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=190)),
                ('answer', i18nfield.fields.I18nCharField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pretix_order_questions.orderquestion')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'unique_together': {('question', 'identifier')},
            },
        ),
    ]
